CRITICAL:root:Message: Element <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is not clickable at point (794,677) because another element <div class="_1mf _1mj"> obscures it
Traceback (most recent call last):
  File "getcomments.py", line 172, in <module>
    main()
  File "getcomments.py", line 155, in main
    browser =  browseURL(url)
  File "getcomments.py", line 131, in browseURL
    more_comments_btn.click()
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is not clickable at point (794,677) because another element <div class="_1mf _1mj"> obscures it

CRITICAL:root:'WebDriver' object has no attribute 'executeScript'
Traceback (most recent call last):
  File "getcomments.py", line 173, in <module>
    main()
  File "getcomments.py", line 156, in main
    browser =  browseURL(url)
  File "getcomments.py", line 131, in browseURL
    browser.executeScript("arguments[0].scrollIntoView(true);", more_comments_btn);
AttributeError: 'WebDriver' object has no attribute 'executeScript'
CRITICAL:root:Message: The element reference of <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
Traceback (most recent call last):
  File "getcomments.py", line 185, in <module>
    main()
  File "getcomments.py", line 168, in main
    browser =  browseURL(url)
  File "getcomments.py", line 143, in browseURL
    browser.execute_script("arguments[0].scrollIntoView(true);", more_comments_btn)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

CRITICAL:root:Message: Element <input class="oajrlxb2 rq0escxv f1sip0of hidtqoto e70eycc3 lzcic4wl g5ia77u1 l6v480f0 maa8sdkg s1tcr66n aypy0576 beltcj47 p86d2i9g aot14ch1 kzx2olss oo9gr5id l94mrbxd ekzkrbhg qypqp5cg cxgpxx05 d1544ag0 osnr6wyh tw6a2znq hzawbc8m mklpznj0 o8yuz56k orhr0ox5 nyueuw64 r8n4e5m6 n7wnqh92 c7gk6p64 bs68lrl8 f56r29tw e16z4an2 ei4baabg" name="email" type="email"> is not reachable by keyboard
Traceback (most recent call last):
  File "getcomments.py", line 185, in <module>
    main()
  File "getcomments.py", line 168, in main
    browser =  browseURL(url)
  File "getcomments.py", line 111, in browseURL
    browser.find_element_by_xpath("//input[@aria-label='Email or Phone']").send_keys("dobre.dani.send.garbage@gmail.com")
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input class="oajrlxb2 rq0escxv f1sip0of hidtqoto e70eycc3 lzcic4wl g5ia77u1 l6v480f0 maa8sdkg s1tcr66n aypy0576 beltcj47 p86d2i9g aot14ch1 kzx2olss oo9gr5id l94mrbxd ekzkrbhg qypqp5cg cxgpxx05 d1544ag0 osnr6wyh tw6a2znq hzawbc8m mklpznj0 o8yuz56k orhr0ox5 nyueuw64 r8n4e5m6 n7wnqh92 c7gk6p64 bs68lrl8 f56r29tw e16z4an2 ei4baabg" name="email" type="email"> is not reachable by keyboard

CRITICAL:root:Message: The element reference of <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
Traceback (most recent call last):
  File "getcomments.py", line 200, in <module>
    main()
  File "getcomments.py", line 183, in main
    browser =  browseURL(url)
  File "getcomments.py", line 161, in browseURL
    browser.execute_script("arguments[0].click();", more_comments_btn)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <div class="oajrlxb2 bp9cbjyn g5ia77u1 mtkw9kbi tlpljxtp qensuy8j ppp5ayq2 goun2846 ccm00jje s44p3ltw mk2mc5f4 rt8b4zig n8ej3o3l agehan2d sk4xxmp2 rq0escxv nhd2j8a9 pq6dq46d mg4g778l btwxx1t3 g5gj957u p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x tgvbjcpo hpfvmrgz jb3vyjys p8fzw8mz qt6c0cv9 a8nywdso l9j0dhe7 i1ao9s8h esuyzwwr f1sip0of du4w35lb lzcic4wl abiwlrkh gpro0wi8 m9osqain buofh1pr"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

CRITICAL:root:Message: Unable to locate element: //div[@role='menuitem'][3]
Traceback (most recent call last):
  File "getcomments.py", line 212, in <module>
    main()
  File "getcomments.py", line 197, in main
    browser =  browseURL(url, user, pwd)
  File "getcomments.py", line 130, in browseURL
    relevant_filter.find_element_by_xpath("//div[@role='menuitem'][3]").click()
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@role='menuitem'][3]

CRITICAL:root:Message: Unable to locate element: //ul/following-sibling::div//div[@role='button']
Traceback (most recent call last):
  File "getcomments.py", line 212, in <module>
    main()
  File "getcomments.py", line 197, in main
    browser =  browseURL(url, user, pwd)
  File "getcomments.py", line 147, in browseURL
    more_comments_btn = comments_box.find_element_by_xpath("//ul/following-sibling::div//div[@role='button']")
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 659, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dani\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //ul/following-sibling::div//div[@role='button']

